### PR TITLE
add multi arch build via GHA

### LINKED ISSUE #3: default image fails to start on ARM64
Starting the image on Mac with M1 ARM64 chip fails with [1].
Introduce cross-platform build for ARM64.  ES provides images for ARM64 (e.g. https://hub.docker.com/layers/elasticsearch/library/elasticsearch/7.11.1/images/sha256-d52cda1e73d1b1915ba2d76ca1e426620c7b5d6942d9d2f432259503974ba786?context=explore)
Starting from the image re-built locally on ARM64 machine works.

[1]
```
$ docker logs elasticsearch-deploy_es_1
+ bin/elasticsearch-keystore create
Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore
+ '[' -f /run/secrets/s3_access_key ']'
+ '[' -f /run/secrets/s3_secret_key ']'
+ bin/elasticsearch-keystore list
keystore.seed
+ /usr/local/bin/docker-entrypoint.sh
Exception in thread "main" java.io.IOException: Cannot run program "/usr/share/elasticsearch/jdk/bin/java": error=0, Failed to exec spawn helper: pid: 435, exit value: 1
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:107)
        at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 435, exit value: 1
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
        ... 6 more
+ bin/elasticsearch-keystore create
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x000000401e9cb224, pid=16, tid=93
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (15.0.1+9) (build 15.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (15.0.1+9, mixed mode, sharing, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# J 70 c1 java.lang.Math.min(II)I java.base@15.0.1 (11 bytes) @ 0x000000401e9cb224 [0x000000401e9cb220+0x0000000000000004]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr/share/elasticsearch/hs_err_pid16.log
Compiled method (c1)    2821   70       3       java.lang.Math::min (11 bytes)
 total in heap  [0x000000401e9cb090,0x000000401e9cb3a0] = 784
 relocation     [0x000000401e9cb1e8,0x000000401e9cb210] = 40
 main code      [0x000000401e9cb220,0x000000401e9cb320] = 256
 stub code      [0x000000401e9cb320,0x000000401e9cb350] = 48
 metadata       [0x000000401e9cb350,0x000000401e9cb358] = 8
 scopes data    [0x000000401e9cb358,0x000000401e9cb368] = 16
 scopes pcs     [0x000000401e9cb368,0x000000401e9cb398] = 48
 dependencies   [0x000000401e9cb398,0x000000401e9cb3a0] = 8
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
qemu: uncaught target signal 6 (Aborted) - core dumped
bin/elasticsearch-keystore: line 6:    16 Aborted                 ES_MAIN_CLASS=org.elasticsearch.common.settings.KeyStoreCli ES_ADDITIONAL_CLASSPATH_DIRECTORIES=lib/tools/keystore-cli "`dirname "$0"`"/elasticsearch-cli "$@"
+ bin/elasticsearch-keystore create
Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
        at org.elasticsearch.cli.Terminal$SystemTerminal.readText(Terminal.java:262)
        at org.elasticsearch.cli.Terminal.promptYesNo(Terminal.java:141)
        at org.elasticsearch.common.settings.CreateKeyStoreCommand.execute(CreateKeyStoreCommand.java:40)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:32)
+ bin/elasticsearch-keystore create
Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
        at org.elasticsearch.cli.Terminal$SystemTerminal.readText(Terminal.java:262)
        at org.elasticsearch.cli.Terminal.promptYesNo(Terminal.java:141)
        at org.elasticsearch.common.settings.CreateKeyStoreCommand.execute(CreateKeyStoreCommand.java:40)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:32)
+ bin/elasticsearch-keystore create
```

### PR DESCRIPTION
**Pull request by konstan**
ARM64 image builds correctly (see https://hub.docker.com/layers/nuvla/es/multi-arch/images/sha256-b31c792ce7052ea7421a0ff14a45c9d9b15c6037945351a0869c2b6731676d2e?context=repo
) and works on Mac M1 chip.

Fixes #3

### CODE REVIEW

**Comment by konstan** [comment]
@0xbase12 Looks like we are building on Travis as well. Is it needed?

**Comment by 0xbase12** [comment]
Not needed

**Comment by 0xbase12** [comment]
LGTM

**Comment by konstan** [comment]
I will disable build on Travis.

**Pull request merged**
